/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.Registros;

/**
 *
 * @author gelog
 */
public class JfRegistroRuta extends javax.swing.JFrame {

    /**
     * Creates new form JfRegistroRuta
     */
    public JfRegistroRuta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnlLienzo = new javax.swing.JPanel();
        JlblOrigen = new javax.swing.JLabel();
        JlblDestino = new javax.swing.JLabel();
        JlblNombre = new javax.swing.JLabel();
        JlblDistancia = new javax.swing.JLabel();
        JlblDuracion = new javax.swing.JLabel();
        JlblHLlegada = new javax.swing.JLabel();
        JlblHSalida = new javax.swing.JLabel();
        JlblPrecio = new javax.swing.JLabel();
        JcmbxOrigenes = new javax.swing.JComboBox<>();
        JcmbxDestinos = new javax.swing.JComboBox<>();
        JtxtNombre = new javax.swing.JTextField();
        JtxtDistancia = new javax.swing.JTextField();
        JtxtDuracion = new javax.swing.JTextField();
        JtxtHSalida = new javax.swing.JTextField();
        JtxtLlegada = new javax.swing.JTextField();
        JtxtPrecio = new javax.swing.JTextField();
        JspNombre = new javax.swing.JSeparator();
        JspDistancia = new javax.swing.JSeparator();
        JspDuracion = new javax.swing.JSeparator();
        JspHS = new javax.swing.JSeparator();
        JspHLL = new javax.swing.JSeparator();
        JspP = new javax.swing.JSeparator();
        JbtnEnviar = new javax.swing.JButton();
        JlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar rutas");
        setResizable(false);

        JpnlLienzo.setBackground(new java.awt.Color(255, 255, 255));
        JpnlLienzo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlblOrigen.setText("Origen");
        JpnlLienzo.add(JlblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        JlblDestino.setText("Destino");
        JpnlLienzo.add(JlblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, -1, -1));

        JlblNombre.setText("Nombre de la ruta");
        JpnlLienzo.add(JlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        JlblDistancia.setText("Distancia");
        JpnlLienzo.add(JlblDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        JlblDuracion.setText("Duracion");
        JpnlLienzo.add(JlblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        JlblHLlegada.setText("Hora de salida");
        JpnlLienzo.add(JlblHLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        JlblHSalida.setText("Hora de llegada");
        JpnlLienzo.add(JlblHSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        JlblPrecio.setText("Precio");
        JpnlLienzo.add(JlblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        JcmbxOrigenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion" }));
        JpnlLienzo.add(JcmbxOrigenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 170, -1));

        JcmbxDestinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion" }));
        JpnlLienzo.add(JcmbxDestinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 106, 170, -1));

        JtxtNombre.setBorder(null);
        JpnlLienzo.add(JtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        JtxtDistancia.setBorder(null);
        JpnlLienzo.add(JtxtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, -1));

        JtxtDuracion.setBorder(null);
        JpnlLienzo.add(JtxtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, -1));

        JtxtHSalida.setBorder(null);
        JpnlLienzo.add(JtxtHSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, -1));

        JtxtLlegada.setBorder(null);
        JpnlLienzo.add(JtxtLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 165, -1));

        JtxtPrecio.setBorder(null);
        JpnlLienzo.add(JtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 165, -1));
        JpnlLienzo.add(JspNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 10));
        JpnlLienzo.add(JspDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 10));
        JpnlLienzo.add(JspDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, 10));
        JpnlLienzo.add(JspHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 180, 10));
        JpnlLienzo.add(JspHLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 180, 10));
        JpnlLienzo.add(JspP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, 10));

        JbtnEnviar.setBackground(new java.awt.Color(160, 16, 70));
        JbtnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnEnviar.setText("Enviar");
        JpnlLienzo.add(JbtnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        JlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoRuta.png"))); // NOI18N
        JpnlLienzo.add(JlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfRegistroRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfRegistroRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfRegistroRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfRegistroRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfRegistroRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnEnviar;
    private javax.swing.JComboBox<String> JcmbxDestinos;
    private javax.swing.JComboBox<String> JcmbxOrigenes;
    private javax.swing.JLabel JlblDestino;
    private javax.swing.JLabel JlblDistancia;
    private javax.swing.JLabel JlblDuracion;
    private javax.swing.JLabel JlblFondo;
    private javax.swing.JLabel JlblHLlegada;
    private javax.swing.JLabel JlblHSalida;
    private javax.swing.JLabel JlblNombre;
    private javax.swing.JLabel JlblOrigen;
    private javax.swing.JLabel JlblPrecio;
    private javax.swing.JPanel JpnlLienzo;
    private javax.swing.JSeparator JspDistancia;
    private javax.swing.JSeparator JspDuracion;
    private javax.swing.JSeparator JspHLL;
    private javax.swing.JSeparator JspHS;
    private javax.swing.JSeparator JspNombre;
    private javax.swing.JSeparator JspP;
    private javax.swing.JTextField JtxtDistancia;
    private javax.swing.JTextField JtxtDuracion;
    private javax.swing.JTextField JtxtHSalida;
    private javax.swing.JTextField JtxtLlegada;
    private javax.swing.JTextField JtxtNombre;
    private javax.swing.JTextField JtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
