/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.Registros;

/**
 *
 * @author gelog
 */
public class JfRegistroAutobuses extends javax.swing.JFrame {

    /**
     * Creates new form JfRegistroAutobuses
     */
    public JfRegistroAutobuses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnlLienzo = new javax.swing.JPanel();
        JlblPlaca = new javax.swing.JLabel();
        JtxtPlaca = new javax.swing.JTextField();
        JspPlaca = new javax.swing.JSeparator();
        JlblCapacidad = new javax.swing.JLabel();
        JtxtCapacidad = new javax.swing.JTextField();
        JspCapacidad = new javax.swing.JSeparator();
        JlblMarca = new javax.swing.JLabel();
        JtxtMarca = new javax.swing.JTextField();
        JspMarca = new javax.swing.JSeparator();
        JlblModelo = new javax.swing.JLabel();
        JtxtModelo = new javax.swing.JTextField();
        JspModelo = new javax.swing.JSeparator();
        JlblAnioR = new javax.swing.JLabel();
        JtxtAnioR = new javax.swing.JTextField();
        JspAnioR = new javax.swing.JSeparator();
        JlblDia = new javax.swing.JLabel();
        JtxtDia = new javax.swing.JTextField();
        JspDia = new javax.swing.JSeparator();
        JlblAnioE = new javax.swing.JLabel();
        JtxtAnioE = new javax.swing.JTextField();
        JspAnioE = new javax.swing.JSeparator();
        JcmbxMeses = new javax.swing.JComboBox<>();
        JbtnEnviar = new javax.swing.JButton();
        JlblNumEconomico = new javax.swing.JLabel();
        JtxtNumEconomico = new javax.swing.JTextField();
        JspNumEconomico = new javax.swing.JSeparator();
        JlblFondo = new javax.swing.JLabel();
        JlblMesRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar autobuses");
        setResizable(false);

        JpnlLienzo.setBackground(new java.awt.Color(255, 255, 255));
        JpnlLienzo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlblPlaca.setText("Placa");
        JpnlLienzo.add(JlblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, -1));

        JtxtPlaca.setBorder(null);
        JpnlLienzo.add(JtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 129, -1));
        JpnlLienzo.add(JspPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 129, 10));

        JlblCapacidad.setText("Capacidad");
        JpnlLienzo.add(JlblCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 60, -1));

        JtxtCapacidad.setBorder(null);
        JpnlLienzo.add(JtxtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 129, -1));
        JpnlLienzo.add(JspCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 129, 10));

        JlblMarca.setText("Marca");
        JpnlLienzo.add(JlblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 129, -1));

        JtxtMarca.setBorder(null);
        JpnlLienzo.add(JtxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 129, -1));
        JpnlLienzo.add(JspMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 129, 10));

        JlblModelo.setText("Modelo");
        JpnlLienzo.add(JlblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 129, -1));

        JtxtModelo.setBorder(null);
        JpnlLienzo.add(JtxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 129, -1));
        JpnlLienzo.add(JspModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 129, 10));

        JlblAnioR.setText("Año de Registro");
        JpnlLienzo.add(JlblAnioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 129, -1));

        JtxtAnioR.setBorder(null);
        JpnlLienzo.add(JtxtAnioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 129, -1));
        JpnlLienzo.add(JspAnioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 129, 10));

        JlblDia.setText("Dia de Registro");
        JpnlLienzo.add(JlblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 129, -1));

        JtxtDia.setBorder(null);
        JpnlLienzo.add(JtxtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 129, -1));
        JpnlLienzo.add(JspDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 129, 10));

        JlblAnioE.setText("Año de Emision");
        JpnlLienzo.add(JlblAnioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 129, -1));

        JtxtAnioE.setBorder(null);
        JpnlLienzo.add(JtxtAnioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 129, -1));
        JpnlLienzo.add(JspAnioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 129, 10));

        JcmbxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        JpnlLienzo.add(JcmbxMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 160, -1));

        JbtnEnviar.setBackground(new java.awt.Color(160, 16, 70));
        JbtnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnEnviar.setText("Enviar");
        JpnlLienzo.add(JbtnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 80, -1));

        JlblNumEconomico.setText("Numero Economico");
        JpnlLienzo.add(JlblNumEconomico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 129, -1));

        JtxtNumEconomico.setBorder(null);
        JpnlLienzo.add(JtxtNumEconomico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 129, -1));
        JpnlLienzo.add(JspNumEconomico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 129, 10));

        JlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoRegistroAutobuses.png"))); // NOI18N
        JpnlLienzo.add(JlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 260));

        JlblMesRegistro.setText("Mes de Registro");
        JpnlLienzo.add(JlblMesRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfRegistroAutobuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfRegistroAutobuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfRegistroAutobuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfRegistroAutobuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfRegistroAutobuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnEnviar;
    private javax.swing.JComboBox<String> JcmbxMeses;
    private javax.swing.JLabel JlblAnioE;
    private javax.swing.JLabel JlblAnioR;
    private javax.swing.JLabel JlblCapacidad;
    private javax.swing.JLabel JlblDia;
    private javax.swing.JLabel JlblFondo;
    private javax.swing.JLabel JlblMarca;
    private javax.swing.JLabel JlblMesRegistro;
    private javax.swing.JLabel JlblModelo;
    private javax.swing.JLabel JlblNumEconomico;
    private javax.swing.JLabel JlblPlaca;
    private javax.swing.JPanel JpnlLienzo;
    private javax.swing.JSeparator JspAnioE;
    private javax.swing.JSeparator JspAnioR;
    private javax.swing.JSeparator JspCapacidad;
    private javax.swing.JSeparator JspDia;
    private javax.swing.JSeparator JspMarca;
    private javax.swing.JSeparator JspModelo;
    private javax.swing.JSeparator JspNumEconomico;
    private javax.swing.JSeparator JspPlaca;
    private javax.swing.JTextField JtxtAnioE;
    private javax.swing.JTextField JtxtAnioR;
    private javax.swing.JTextField JtxtCapacidad;
    private javax.swing.JTextField JtxtDia;
    private javax.swing.JTextField JtxtMarca;
    private javax.swing.JTextField JtxtModelo;
    private javax.swing.JTextField JtxtNumEconomico;
    private javax.swing.JTextField JtxtPlaca;
    // End of variables declaration//GEN-END:variables
}
