/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.Registros;

/**
 *
 * @author gelog
 */
public class JfRegistroTerminal extends javax.swing.JFrame {

    /**
     * Creates new form JfRegistroDireccion
     */
    public JfRegistroTerminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnlLienzo = new javax.swing.JPanel();
        JlblEstado = new javax.swing.JLabel();
        JtxtEstado = new javax.swing.JTextField();
        JspEstado = new javax.swing.JSeparator();
        JlblCiudad = new javax.swing.JLabel();
        JtxtCiudad = new javax.swing.JTextField();
        JspCiudad = new javax.swing.JSeparator();
        JlblCalle = new javax.swing.JLabel();
        JtxtCalle = new javax.swing.JTextField();
        JspCalle = new javax.swing.JSeparator();
        JlblBarrio = new javax.swing.JLabel();
        JtxtBarrio = new javax.swing.JTextField();
        JspBarrio = new javax.swing.JSeparator();
        JlblCP = new javax.swing.JLabel();
        JtxtCP = new javax.swing.JTextField();
        JspCP = new javax.swing.JSeparator();
        JlblNumero = new javax.swing.JLabel();
        JtxtNumero = new javax.swing.JTextField();
        JspNumerp = new javax.swing.JSeparator();
        JbtnEnviar = new javax.swing.JButton();
        JlblNombreTerminal = new javax.swing.JLabel();
        JtxtNombreTerminal = new javax.swing.JTextField();
        JspNombreTerminal = new javax.swing.JSeparator();
        JlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar terminales");
        setResizable(false);

        JpnlLienzo.setBackground(new java.awt.Color(255, 255, 255));
        JpnlLienzo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlblEstado.setText("Estado");
        JpnlLienzo.add(JlblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        JtxtEstado.setBorder(null);
        JpnlLienzo.add(JtxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, -1));
        JpnlLienzo.add(JspEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));

        JlblCiudad.setText("Ciudad");
        JpnlLienzo.add(JlblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        JtxtCiudad.setBorder(null);
        JpnlLienzo.add(JtxtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));
        JpnlLienzo.add(JspCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, -1));

        JlblCalle.setText("Nombre de la vialidad");
        JpnlLienzo.add(JlblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        JtxtCalle.setBorder(null);
        JpnlLienzo.add(JtxtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, -1));
        JpnlLienzo.add(JspCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 10));

        JlblBarrio.setText("Colonia/Barrio");
        JpnlLienzo.add(JlblBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        JtxtBarrio.setBorder(null);
        JpnlLienzo.add(JtxtBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, -1));
        JpnlLienzo.add(JspBarrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, -1));

        JlblCP.setText("Codigo Postal");
        JpnlLienzo.add(JlblCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        JtxtCP.setBorder(null);
        JpnlLienzo.add(JtxtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 110, -1));
        JpnlLienzo.add(JspCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 110, -1));

        JlblNumero.setText("Numero");
        JpnlLienzo.add(JlblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        JtxtNumero.setBorder(null);
        JpnlLienzo.add(JtxtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 110, -1));
        JpnlLienzo.add(JspNumerp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 110, -1));

        JbtnEnviar.setBackground(new java.awt.Color(160, 16, 70));
        JbtnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        JbtnEnviar.setText("Enviar");
        JpnlLienzo.add(JbtnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 70, -1));

        JlblNombreTerminal.setText("Nombre");
        JpnlLienzo.add(JlblNombreTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JtxtNombreTerminal.setBorder(null);
        JpnlLienzo.add(JtxtNombreTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, -1));
        JpnlLienzo.add(JspNombreTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, -1));

        JlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoRegistroTerminal.png"))); // NOI18N
        JpnlLienzo.add(JlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 200, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnlLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfRegistroTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfRegistroTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfRegistroTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfRegistroTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfRegistroTerminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnEnviar;
    private javax.swing.JLabel JlblBarrio;
    private javax.swing.JLabel JlblCP;
    private javax.swing.JLabel JlblCalle;
    private javax.swing.JLabel JlblCiudad;
    private javax.swing.JLabel JlblEstado;
    private javax.swing.JLabel JlblFondo;
    private javax.swing.JLabel JlblNombreTerminal;
    private javax.swing.JLabel JlblNumero;
    private javax.swing.JPanel JpnlLienzo;
    private javax.swing.JSeparator JspBarrio;
    private javax.swing.JSeparator JspCP;
    private javax.swing.JSeparator JspCalle;
    private javax.swing.JSeparator JspCiudad;
    private javax.swing.JSeparator JspEstado;
    private javax.swing.JSeparator JspNombreTerminal;
    private javax.swing.JSeparator JspNumerp;
    private javax.swing.JTextField JtxtBarrio;
    private javax.swing.JTextField JtxtCP;
    private javax.swing.JTextField JtxtCalle;
    private javax.swing.JTextField JtxtCiudad;
    private javax.swing.JTextField JtxtEstado;
    private javax.swing.JTextField JtxtNombreTerminal;
    private javax.swing.JTextField JtxtNumero;
    // End of variables declaration//GEN-END:variables
}
